# Import pandas library

In [32]:
import pandas as pd

# Sample Datasets

In [33]:
Data = {
   'Department': ['HR', 'IT', 'IT', 'HR', 'Finance'],
    'Salary': [40000, 60000, None, 45000, 70000]
}

In [34]:
df = pd.DataFrame(Data)

In [35]:
df.head(2)

  Department   Salary
0         HR  40000.0
1         IT  60000.0

# Remove missing Values

In [36]:
df = df.dropna()

In [37]:
df.head(4)

  Department   Salary
0         HR  40000.0
1         IT  60000.0
3         HR  45000.0
4    Finance  70000.0

# Grouping and Aggregation

In [38]:
Avg_Salary = df.groupby('Department')['Salary'].mean()

In [39]:
print("Average Salary by Department:")
print(Avg_Salary)

Average Salary by Department:
Department
Finance    70000.0
HR         42500.0
IT         60000.0
Name: Salary, dtype: float64